name: Holon Rental Monitor

on:
  workflow_dispatch:
  schedule:
      - cron: "*/15 * * * *"

jobs:
 monitor:
  runs-on: ubuntu-latest

  steps:
   - uses: actions/checkout@v4

   - uses: actions/setup-python@v5
     with:
       python-version: "3.11"

   - name: Install dependencies
     run: |
       pip install -r requirements.txt

   - name: Run monitor
     env:
       APIFY_TOKEN: ${{ secrets.APIFY_TOKEN }}
     run: |
        python main.py
